Made reactive
gznznzjsn/employee-service pull request #4
Opened 2023-03-10 13:08 UTC by gznznzjsn

2023-03-10 15:18 UTC, h1alexbel requested changes
@gznznzjsn remove comments, please

2023-03-10 15:18 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/service/impl/EmployeeServiceImpl.java
> +    //    public Mono<ServerResponse> hello(ServerRequest request) {
remove comments

2023-03-10 15:18 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/web/controller/EmployeeController.java
> +    //    @PreAuthorize("hasAuthority('EMPLOYEE_MANAGER')")
comments

2023-03-10 15:18 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/web/controller/EmployeeController.java
> +    //    @PreAuthorize("hasAuthority('EMPLOYEE_MANAGER')")
comments

2023-03-10 15:18 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/web/controller/EmployeeController.java
> +    //    @PreAuthorize("hasAuthority('EMPLOYEE_MANAGER')")
again comments

2023-03-10 15:18 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/web/controller/EmployeeController.java
> +    //    @PreAuthorize("hasAuthority('EMPLOYEE_MANAGER')")
comments

2023-03-13 11:17 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/service/impl/EmployeeServiceImpl.java
> +    //    public Mono<ServerResponse> hello(ServerRequest request) {
done

2023-03-13 11:24 UTC, h1alexbel approved these changes

2023-03-13 11:25 UTC, h1alexbel commented
@gznznzjsn, please name your pull request properly!

2023-03-13 11:25 UTC, merged