CQRS
gznznzjsn/employee-service pull request #6
Opened 2023-03-27 08:34 UTC by gznznzjsn

2023-03-28 08:07 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/commandapi/event/handler/PeriodEventHandler.java
> +                                new ResourceNotFoundException("Periods with id = " + periodId + " not found!")
I will slash this line in pull request with saga today

2023-03-28 11:11 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/commandapi/event/handler/PeriodEventHandler.java
> +                                new ResourceNotFoundException("Periods with id = " + periodId + " not found!")
@gznznzjsn well, I believe we need to implement event sourcing on the persistence layer to have out some virtues of event sourcing such as event audit, event state immutability, and cqrs virtues: segregation of command API and query API

2023-03-28 14:59 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/commandapi/event/handler/PeriodEventHandler.java
> +                                new ResourceNotFoundException("Periods with id = " + periodId + " not found!")
But events are persisted as well, and we can access their aggregates with commands. No doubt, we can use them for reading too, but in this case I use separate database for queries, which stores not events, but common objects, more convenient for reading

2023-03-29 12:08 UTC, h1alexbel requested changes
@gznznzjsn to improve the application read performance I recommend storing aggregate in the database to have the ability to query the last state of aggregate and apply a new patch to it.

2023-03-29 12:08 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/queryapi/query/handler/EmployeeQueryHandler.java
> +        return repository.findAllByGlossary_Id(query.getGlossaryId()).collectList().block();
please, follow Java code [conventions](https://www.oracle.com/technetwork/java/codeconventions-150003.pdf)

2023-03-29 12:08 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/queryapi/query/handler/EmployeeQueryHandler.java
> +                                new ResourceNotFoundException("Employee with id=" + query.getEmployeeId() + " not found!") //todo message
line is too long

2023-03-29 12:08 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/queryapi/query/handler/EmployeeQueryHandler.java
> +                ).block();
don't use block in reactive context

2023-03-29 12:08 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/queryapi/service/impl/EmployeeQueryServiceImpl.java
> +        return queryGateway.query(getAllEmployeesQuery, ResponseTypes.multipleInstancesOf(Employee.class)).flatMapMany(Flux::fromIterable);
what the implementation inside the `query()` method?

2023-03-29 12:08 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/saga/EmployeeCreationSaga.java
> +    public void handle(EmployeeCreatedEvent event) {
method declaration in the class

2023-03-29 12:08 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/saga/EmployeeCreationSaga.java
> +                .subscribe();
use schedulers, but don't use `subscribe`

2023-03-29 13:40 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/queryapi/service/impl/EmployeeQueryServiceImpl.java
> +        return queryGateway.query(getAllEmployeesQuery, ResponseTypes.multipleInstancesOf(Employee.class)).flatMapMany(Flux::fromIterable);
It asynchronously sends query to QueryBus and expects response. But I thought a bit and considered to replace it with just EmployeeQueryHandler method call in upcoming commit so it will remove block in previous comments

2023-03-29 13:59 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/saga/EmployeeCreationSaga.java
> +                .subscribe();
Can you, please, specify what you mean?

2023-03-29 14:08 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/saga/EmployeeCreationSaga.java
> +                .subscribe();
@h1alexbel

2023-03-29 14:15 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/saga/EmployeeCreationSaga.java
> +                .subscribe();
@gznznzjsn 
https://egkatzioura.com/2021/10/11/executing-blocking-calls-on-a-reactor-based-application/

2023-03-29 14:34 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/saga/EmployeeCreationSaga.java
> +                .subscribe();
thank you

2023-03-29 15:17 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/saga/EmployeeCreationSaga.java
> +                .subscribe();
I don't really understand how can it be implemented in our case. As I understood, Schedulers are used for calling blocking methods in non-blocking context, but, in this case, we need to call non-blocking method in blocking context. SagaEventHandler must return void, so it is blocking

2023-03-29 15:19 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/commandapi/aggregate/GlossaryAggregate.java
> +                        new ResourceNotFoundException("No free time periods for such parameters: arrival time = " + arrivalTime + ", specialization = " + specialization.name() + ", total assignment d
Done

2023-03-29 15:19 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/commandapi/aggregate/GlossaryAggregate.java
> +public class GlossaryAggregate {
Done

2023-03-29 15:19 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/queryapi/query/handler/EmployeeQueryHandler.java
> +        return repository.findAllByGlossary_Id(query.getGlossaryId()).collectList().block();
Done

2023-03-29 15:19 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/queryapi/query/handler/EmployeeQueryHandler.java
> +                                new ResourceNotFoundException("Employee with id=" + query.getEmployeeId() + " not found!") //todo message
Done

2023-03-29 15:20 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/queryapi/query/handler/EmployeeQueryHandler.java
> +                ).block();
Done

2023-03-29 15:20 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/saga/EmployeeCreationSaga.java
> +    public void handle(EmployeeCreatedEvent event) {
Done

2023-03-29 15:20 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/commandapi/event/handler/EmployeeEventHandler.java
> +    public void on(EmployeeCreatedEvent event) {
Done

2023-03-29 15:44 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/saga/EmployeeCreationSaga.java
> +                .subscribe();
@h1alexbel

2023-03-29 17:36 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/saga/EmployeeCreationSaga.java
> +                .subscribe();
> I don't really understand how can it be implemented in our case. As I understood, Schedulers are used for calling blocking methods in non-blocking context, but, in this case, we need to call non-blocking method in blocking context. SagaEventHandler must return void, so it is blocking

@gznznzjsn so, you don't need a reactive paradigm here

2023-03-29 20:08 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/saga/EmployeeCreationSaga.java
> +                .subscribe();
Makes sense

2023-03-29 20:37 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/saga/EmployeeCreationSaga.java
> +                .subscribe();
Done

2023-03-30 16:24 UTC, h1alexbel requested changes
quite big PR. try to make it smaller

2023-03-30 16:24 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/commandapi/event/handler/PeriodEventHandler.java
> +    public void on(PeriodCreatedEvent event) {
method is declared in concrete class

2023-03-30 16:24 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/commandapi/event/handler/PeriodEventHandler.java
> +    public void on(PeriodDeletedEvent event) {
method is declared in concrete class

2023-03-30 22:02 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/commandapi/aggregate/GlossaryAggregate.java
> +public class GlossaryAggregate implements EmployeeCommandHandler, PeriodCommandHandler, EmployeeSourcingHandler, PeriodSourcingHandler {
Moved command handlers to two separate classes

2023-03-30 22:02 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/commandapi/aggregate/GlossaryAggregate.java
> +                        new ResourceNotFoundException("No periods with id = " + event.getPeriodId()));
Done

2023-03-30 22:03 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/commandapi/event/handler/PeriodEventHandler.java
> +    public void on(PeriodCreatedEvent event) {
Moved declaration to interface

2023-03-31 19:20 UTC, gznznzjsn commented
@h1alexbel please, review this pr

2023-03-31 21:00 UTC, h1alexbel requested changes

2023-03-31 21:00 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/queryapi/service/impl/EmployeeQueryServiceImpl.java
> +    private final EmployeeQueryHandlerImpl queryHandler;
only interfaces should be injected

2023-04-02 18:50 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/queryapi/service/impl/EmployeeQueryServiceImpl.java
> +    private final EmployeeQueryHandlerImpl queryHandler;
yeah, didn't notice)

2023-04-03 05:28 UTC, h1alexbel approved these changes

2023-04-03 05:28 UTC, merged