Dockerized
gznznzjsn/employee-service pull request #7
Opened 2023-04-13 09:52 UTC by gznznzjsn

2023-04-13 11:21 UTC, h1alexbel requested changes

2023-04-13 11:21 UTC, h1alexbel commented on .github/workflows/image-push.yml
> +    runs-on: ubuntu-latest
@gznznzjsn use specific version instead the latest one

2023-04-13 11:21 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/employeeservice/commandapi/command/EmployeeCreateCommand.java
> +    @TargetAggregateIdentifier
@gznznzjsn how these changes are related to the dockerization?

2023-04-13 14:14 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/employeeservice/commandapi/command/EmployeeCreateCommand.java
> +    @TargetAggregateIdentifier
Without it, workflow won't work properly. Previously this class was in separated module, used in two services. So, it is just a small fix for proper workflow

2023-04-14 10:53 UTC, h1alexbel approved these changes

2023-04-14 10:53 UTC, merged